### ISSUE TITLE
Check presence of debsums

### ISSUE THREAD

**Issue by lcheylus** [YJesus/RCLocals#1]
When I first launch your tool, I have an error because of `debsums` tool missing : 
```
[*Checking file integrity*]

/bin/sh: 1: debsums: not found
```
The tool needs to check first if necessary tools are present on the system and display a error message if not.

**Comment by YJesus** [comment]
You are right, I'm going to update the usage advertising this 

Thank you !!

**Comment by YJesus** [comment]
I have add info in README about debsums and non standard Python modules
